### PR TITLE
Fix panic when changing from ephemeral storage to pvcs

### LINKED ISSUE #600: Operator panics when changing from ephemeral storage to PVCs
Issue was reported in Opni - https://github.com/rancher/opni/issues/1700
```[04:08:04] INFO Generating certificates {"controller": "opensearchcluster", "controllerGroup": "[opensearch.opster.io](http://opensearch.opster.io/)", "controllerKind": "OpenSearchCluster", "OpenSearchCluster": {"name":"opni","namespace":"opni"}, "namespace": "opni", "name": "opni", "reconcileID": "11a160f3-966e-4979-b16f-b5848f1a51a6", "interface": "http"}
[04:08:04] INFO updating existing ism {"controller": "multiclusterrolebinding", "controllerGroup": "[logging.opni.io](http://logging.opni.io/)", "controllerKind": "MulticlusterRoleBinding", "MulticlusterRoleBinding": {"name":"opni","namespace":"opni"}, "namespace": "opni", "name": "opni", "reconcileID": "c3431a0e-56c2-4e53-b119-21012136273a", "policy": "log-policy"}
[04:08:04] INFO Observed a panic in reconciler: runtime error: index out of range [0] with length 0 {"controller": "opensearchcluster", "controllerGroup": "[opensearch.opster.io](http://opensearch.opster.io/)", "controllerKind": "OpenSearchCluster", "OpenSearchCluster": {"name":"opni","namespace":"opni"}, "namespace": "opni", "name": "opni", "reconcileID": "11a160f3-966e-4979-b16f-b5848f1a51a6"}
panic: runtime error: index out of range [0] with length 0 [recovered]
        panic: runtime error: index out of range [0] with length 0
goroutine 880 [running]:
[sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()](http://sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1())
        [sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:115](http://sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:115) +0x1e5
panic({0x488cea0?, 0xc003f9b260?})
        runtime/panic.go:914 +0x21f
[opensearch.opster.io/pkg/reconcilers.(*ClusterReconciler).reconcileNodeStatefulSet(_](http://opensearch.opster.io/pkg/reconcilers.(*ClusterReconciler).reconcileNodeStatefulSet(_), {{0xc001b3818c, 0x4}, 0x3, {0xc001b38190, 0x4}, {0xc0016ffc20, 0xc0016ffc50, {0x0, 0x0, ...}}, ...}, ...)
        opensearch.opster.io@v0.0.0-00010101000000-000000000000/pkg/reconcilers/cluster.go:308 +0x1f18
[opensearch.opster.io/pkg/reconcilers.(*ClusterReconciler).Reconcile(0xc00046abd0)](http://opensearch.opster.io/pkg/reconcilers.(*ClusterReconciler).Reconcile(0xc00046abd0))
        opensearch.opster.io@v0.0.0-00010101000000-000000000000/pkg/reconcilers/cluster.go:120 +0x9b0
[opensearch.opster.io/controllers.(*OpenSearchClusterReconciler).reconcilePhaseRunning(0xc001030a50](http://opensearch.opster.io/controllers.(*OpenSearchClusterReconciler).reconcilePhaseRunning(0xc001030a50), {0x63c5490, 0xc0016ff890})
        opensearch.opster.io@v0.0.0-00010101000000-000000000000/controllers/opensearchController.go:320 +0x7ad
[opensearch.opster.io/controllers.(*OpenSearchClusterReconciler).Reconcile(0xc001030a50](http://opensearch.opster.io/controllers.(*OpenSearchClusterReconciler).Reconcile(0xc001030a50), {0x63c5490, 0xc0016ff890}, {{{0xc001b380e4, 0x4}, {0xc001b380e0, 0x4}}})
        opensearch.opster.io@v0.0.0-00010101000000-000000000000/controllers/opensearchController.go:141 +0x779
[sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x63c5490](http://sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x63c5490)?, {0x63c5490?, 0xc0016ff890?}, {{{0xc001b380e4?, 0x40b50a0?}, {0xc001b380e0?, 0x6399528?}}})
        [sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:118](http://sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:118) +0xb7
[sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000fafb80](http://sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000fafb80), {0x63c54c8, 0xc000f65860}, {0x45f69c0?, 0xc001b8c020?})
        [sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:314](http://sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:314) +0x365
[sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000fafb80](http://sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000fafb80), {0x63c54c8, 0xc000f65860})
        [sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:265](http://sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:265) +0x1c9
[sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()](http://sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2())
        [sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:226](http://sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:226) +0x79
created by [sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2](http://sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2) in goroutine 375
        [sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:222](http://sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:222) +0x565
```

The issue is occurring because the resize logic expects a PVC and a VolumeClaim template to already exist in the statefulset.  When this is the case we need to put in logic for updating the stateful set

### PR DESCRIPTION
**Pull request by dbason**
Fixes #600 

This PR makes the following changes:
- Separates the logic for resizing volumes to a separate function
- Adds a check for if the PVCs already exist and if not just deletes the statefulset (orphaning the pods)
- Inverts the order that we manually rollout pods in.  For the previous change the PVCs are created from lowest ordinal to highest so for this to work the manual rolling restart/upgrade needs to follow this order.

### CODE REVIEW

File: opensearch-operator/pkg/helpers/helpers.go [hunk 1]
```diff
@@ -432,11 +432,11 @@ func WorkingPodForRollingRestart(ctx context.Context, k8sClient client.Client, s
 	replicas := lo.FromPtrOr(sts.Spec.Replicas, 1)
 	// Handle the simple case
 	if replicas == sts.Status.UpdatedReplicas+sts.Status.CurrentReplicas {
-		ordinal := replicas - 1 - sts.Status.UpdatedReplicas
+		ordinal := sts.Status.UpdatedReplicas
 		return ReplicaHostName(*sts, ordinal), nil
 	}
 	// If there are potentially mixed revisions we need to check each pod
-	for i := replicas - 1; i >= 0; i-- {
+	for i := int32(0); i < replicas; i++ {
```
Comment (idanl21) [inline opensearch-operator/pkg/helpers/helpers.go:439]: Can you please explain that change ?

**Review by swoehrl-mw — APPROVED** [review]
LGTM

**Review by idanl21 — APPROVED** [review]
